name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # same as in serverless.yml and Pipfile
          cache: 'pipenv'

      - run: pipenv install --dev
      - run: pipenv run black --check .

  # TODO: doesn't work because we're using implied AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  # in the lambda environment
  # scan-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: npx @eqworks/scan-env --strict

  commit-watch:
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request') # only run on pull requests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npx @eqworks/commit-watch -b ${{ github.event.pull_request.base.sha }} -h ${{ github.event.pull_request.head.sha }} -v
